import Head from "next/head";

import axios from "axios";
import { Menu } from "@/components/Menu/Menu";
import Grid from "@mui/material/Grid";
import { ListSubheader, Paper } from "@mui/material";
import ListMenu from "@/components/Menu/ListMenu/ListMenu";
export default function Home({ menu }) {
  return (
    <>
      <Head>
        <title>Restaurant</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="favicon.ico" />
      </Head>

      <main>
        <Grid container spacing={3} sx={{ mt: 1 }}>
          <Grid item xs>
            <Menu menu={menu}></Menu>
          </Grid>
          <Grid item xs={6}>
            <ListMenu menu={menu}></ListMenu>
          </Grid>
          <Grid item xs>
            <Paper>xs</Paper>
          </Grid>
        </Grid>
      </main>
    </>
  );
}
export async function getServerSideProps() {
  const { data } = await axios.get(`${process.env.BASE_SITE}/api/menu`);
  const menu = data.menu;

  return {
    props: { menu },
  };
}
