import Head from "next/head";

import { MenuCom } from "@/components/Menu/Menu";
import Grid from "@mui/material/Grid";
import { styled } from "@mui/material";
import ListMenu from "@/components/Menu/ListMenu/ListMenu";
import InfoPanel from "@/components/InfoPanel/InfoPanel";
import dbConnect from "@/lib/mongoose";

import Menu from "@/models/Menu";

const GridStyled = styled(Grid)(({ theme }) => ({
  [theme.breakpoints.up("md")]: {
    position: "sticky",
    top: 80,
    alignSelf: "start",
  },
}));
const Home = ({ menu }) => {
  return (
    <>
      <Head>
        <title>Restaurant</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="favicon.ico" />
      </Head>

      <main>
        <Grid container sx={{ mt: 1 }} columnSpacing={3} rowSpacing={1}>
          <GridStyled md={3} xs={12} item>
            <MenuCom menu={menu}></MenuCom>
          </GridStyled>
          <Grid md={6} xs={12} item>
            <ListMenu menu={menu}></ListMenu>
          </Grid>
          <GridStyled md={3} xs={12} item>
            <InfoPanel></InfoPanel>
          </GridStyled>
        </Grid>
      </main>
    </>
  );
};
export const getServerSideProps = async () => {
  await dbConnect();
  const result = await Menu.find({});

  const menus = result.map((doc) => {
    const menu = doc.toObject();
    menu._id = menu._id.toString();
    return menu;
  });
  return {
    props: { menu: menus },
  };
};
export default Home;
